import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./Components/Navbar";
import Footer from "@/app/Components/Footer"; 
import { playfair_display, roboto } from "./utils/fonts";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jaza Perfumes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto}  ${playfair_display}` }>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
